import "./globals.css";
import Link from "next/link";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body >
                <div className="h-full m-2 font-extrabold fixed">
                    <Link href="/" className="text-3xl">
                        Maple Info
                    </Link>
                </div>
                <div className=" pt-14">{children}</div>
            </body>
        </html>
    );
}
