import "./globals.css";
import Link from "next/link";
import Providers from "./providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="kr">
            <body>
                <Providers>
                    <div className="flex flex-col h-screen w-full overflow-hidden">
                        <div className="h-auto m-2 font-bold  w-screen">
                            <Link href="/" className="text-3xl">
                                Maple Info
                            </Link>
                        </div>
                        <div className="flex-grow ">{children}</div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
